name: Link Checker (PR Build)

# Disabled. GitHub doesn't actually stop these jobs from running automatically
# even when they come from untrusted contributors, so this is insecure.
# on:
#   # Note: this job runs with in-repo permissions so it can comment and commit
#   # on stuff in the repo even when the PR is coming from a PR. This means that
#   # it can, potentially, wreak havoc on the repository by running arbitrary
#   # code. Be sure to ONLY approve job runs AFTER you have confirmed that the
#   # commits in question do not contain malicious or suspicious code (especially
#   # to the .sh or .py files in the tool/ directory.)
#   pull_request_target:
#     types: [opened, edited, synchronize]

jobs:
  build:
    name: "Build and Check Links"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: "3.7"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Jinja2==2.11.3
        pip install dactyl lxml

    - name: Check for Conflict Markers
      run: |
        tool/conflictmarkers.sh

    - name: Build docs
      run: |
        echo '{"github_forkurl": "https://github.com/${{ github.event.pull_request.head.repo.full_name }}", "github_branch": "${{ github.head_ref }}", "github_pr_id": "${{ github.event.number }}", "is_pr_build": true}' > dactyl_vars.json
        tool/build_all_langs.sh --vars dactyl_vars.json

    - name: Run Dactyl Link Checker
      continue-on-error: true
      run: |
        dactyl_link_checker -o -q > linkreport.txt

    - name: Assemble Link Report
      run: |
        sed -i '1,/---------------------------------------/d' linkreport.txt
        echo 'LINKREPORT<<EOF' >> $GITHUB_ENV
        cat linkreport.txt >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
        cat linkreport.txt

    - name: Run Style Checker
      continue-on-error: true
      run: dactyl_style_checker -q > out/style_report.txt

    # new deploy system. TODO: delete folders from gh-pages when PRs are closed
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
        destination_dir: ./pr-preview/${{ github.head_ref }}

    - name: Summarize Output
      uses: thollander/actions-comment-pull-request@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: "${{ env.LINKREPORT }}\n\nPreview: https://${{ github.repository_owner }}.github.io/${{ github.event.pull_request.base.repo.name }}/pr-preview/${{ github.head_ref }}/\n\n[Style Report](https://${{ github.repository_owner }}.github.io/${{ github.event.pull_request.base.repo.name }}/pr-preview/${{ github.head_ref }}/style_report.txt)"
